version: '3.8'

services:
  job-portal-staging:
    image: ${DOCKERHUB_USERNAME}/job-portal:staging
    container_name: job-portal-staging-local
    ports:
      - "3001:5000"
    environment:
      - NODE_ENV=staging
      - PORT=5000
      - MONGODB_URI=${STAGING_MONGODB_URI}
      - JWT_SECRET=${STAGING_JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - staging-network

  # Optional: Local MongoDB for staging testing
  mongodb-staging:
    image: mongo:7
    container_name: mongodb-staging-local
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=staging_admin
      - MONGO_INITDB_ROOT_PASSWORD=staging_password
      - MONGO_INITDB_DATABASE=job_portal_staging
    volumes:
      - mongodb_staging_data:/data/db
    networks:
      - staging-network
    profiles:
      - local-db

networks:
  staging-network:
    driver: bridge

volumes:
  mongodb_staging_data: