version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/job-portal
      - JWT_SECRET=your_secure_jwt_secret
      - NODE_ENV=development
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 