version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Choose ONE of these options:
      # Option 1: Use the MongoDB container in docker-compose
      - MONGODB_URI=mongodb://mongo:27017/job-portal
      # Option 2: Use MongoDB on your host machine
      #- MONGODB_URI=mongodb://host.docker.internal:27017/job-portal
      # Option 3: Use a remote MongoDB server
      #- MONGODB_URI=mongodb+srv://yourusername:yourpassword@yourcluster.mongodb.net/job-portal
      - JWT_SECRET=your_secure_jwt_secret
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: 