apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-deployment
  namespace: job-portal
  labels:
    app: job-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
      - name: job-portal
        image: DOCKERHUB_USERNAME/job-portal:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: job-portal-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: job-portal-config
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: job-portal-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: job-portal-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5