apiVersion: v1
kind: Secret
metadata:
  name: job-portal-secrets
  namespace: job-portal
type: Opaque
data:
  # These will be base64 encoded values
  # Use: echo -n "your-value" | base64
  MONGODB_URI: # Add your base64 encoded MongoDB URI
  JWT_SECRET: # Add your base64 encoded JWT secret